---
prometheus_vars:
  kubernetes:
    alertmanager:
      gateway:
        service: monitoring-kube-prometheus-alertmanager
        subdomain: alertmanager
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.21
      log_level: warn
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      retention: 72h
      storage: 5Gi
    helm:
      chart:
        name: kube-prometheus-stack
        prefix: monitoring
        version: v65.5.1
      repository:
        name: helm-charts
        org: prometheus-community
        url: https://prometheus-community.github.io
    grafana:
      gateway:
        service: monitoring-grafana
        subdomain: grafana
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.22
      secret:
        name: grafana-secret
      user:
        name: admin
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66656538353164363765613837386436613538346263653237626564663933326339633664646463
          3233393161333861613831383064616334303232373432330a643665323563323236356336653265
          64366365613439333162323762356361656165633036356138643632396333626162373932623461
          6663663637643765360a656561343638353264303136333430323038313339306439376265373462
          31333461353038343738346665663139303737383963643263616331306364303766
    namespace: kube-system
    prometheus:
      compaction:
        enabled: true
      gateway:
        service: monitoring-kube-prometheus-prometheus
        subdomain: prometheus
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.23
      log_level: warn
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 2.5Gi
        requests:
          cpu: 10m
          memory: 2.5Gi
      retention: 3d
      retention_size: 20GB
      storage: 100Gi
